import { Mission } from "@/lib/types";

export const missions: Mission[] = [
  {
    id: "MISSION_01",
    codename: "PORTFOLIO OS",
    type: "WEB APPLICATION",
    status: "DEPLOYING",
    year: "2026",
    description:
      "A futuristic portfolio website built as an interactive operating system with a cyberpunk HUD interface, terminal access and dynamic modules.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    features: [
      "Cyberpunk HUD interface",
      "Interactive terminal",
      "Dynamic modules",
      "Responsive design",
      "High performance",
    ],
    screenshots: ["DASHBOARD // PROFILE", "MISSION DOSSIER", "TRANSMISSION"],
    liveDemo: "#",
    sourceCode: "https://github.com",
  },
  {
    id: "MISSION_02",
    codename: "AI CODE ASSISTANT",
    type: "DEVELOPER TOOL",
    status: "DEPLOYED",
    year: "2025",
    description:
      "A context-aware coding copilot that indexes a repository, retrieves relevant code, and proposes verified edits through an agentic loop.",
    techStack: ["Python", "FastAPI", "PyTorch", "Postgres", "React"],
    features: [
      "Repo-wide semantic search",
      "Agentic edit + verify loop",
      "Inline diff review",
      "Streaming responses",
      "Local-first privacy mode",
    ],
    screenshots: ["AGENT CONSOLE", "DIFF REVIEW"],
    liveDemo: "#",
    sourceCode: "https://github.com",
  },
  {
    id: "MISSION_03",
    codename: "TASKFLOW PRO",
    type: "SAAS PLATFORM",
    status: "DEPLOYED",
    year: "2025",
    description:
      "A real-time team operations platform with live boards, presence, and automation rules — engineered for sub-100ms collaborative updates.",
    techStack: ["Next.js", "tRPC", "Redis", "WebSockets", "Prisma"],
    features: [
      "Real-time collaborative boards",
      "Presence + cursors",
      "Automation engine",
      "Role-based access",
      "Offline sync",
    ],
    screenshots: ["LIVE BOARD", "AUTOMATION RULES"],
    liveDemo: "#",
    sourceCode: "https://github.com",
  },
  {
    id: "MISSION_04",
    codename: "DATA VISUALIZER",
    type: "ANALYTICS ENGINE",
    status: "COMPLETE",
    year: "2024",
    description:
      "A GPU-accelerated dashboard rendering millions of data points with smooth pan/zoom, built on a custom WebGL charting core.",
    techStack: ["TypeScript", "WebGL", "Rust (WASM)", "ClickHouse"],
    features: [
      "Million-point rendering",
      "Custom WebGL core",
      "WASM aggregation",
      "Time-series drilldown",
      "Exportable reports",
    ],
    screenshots: ["RENDER GRID", "TIME-SERIES"],
    liveDemo: "#",
    sourceCode: "https://github.com",
  },
  {
    id: "MISSION_05",
    codename: "SECURE CHAT APP",
    type: "MOBILE / WEB",
    status: "COMPLETE",
    year: "2024",
    description:
      "End-to-end encrypted messaging with self-destructing transmissions, forward secrecy, and a zero-knowledge backend.",
    techStack: ["React Native", "Go", "libsignal", "gRPC"],
    features: [
      "End-to-end encryption",
      "Forward secrecy",
      "Self-destruct timers",
      "Zero-knowledge sync",
      "Cross-platform",
    ],
    screenshots: ["SECURE THREAD", "KEY EXCHANGE"],
    liveDemo: "#",
    sourceCode: "https://github.com",
  },
];
